# install node and npm
- name: Install GPG
  tags: [nodejs]
  apt:
    name: gnupg
    update_cache: yes
    state: present

# add gpg key for nodesource
- name: Install the gpg key for nodejs LTS
  tags: [nodejs]
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

# add nodesource repository to Ubuntu
- name: Install the nodejs LTS repos
  tags: [nodejs]
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

# install nodejs on server
- name: Install NodeJS
  tags: [nodejs]
  apt:
    name: nodejs
    state: latest

