# Node app setup
- name: Create app directory for node app
  tags: [app]
  file:
    path: /var/www/html/app
    state: directory
    owner: www-data
    group: www-data
    mode: 0604

# copy files needed to setup app on server
- name: Copy package-lock.json to server
  tags: [copy_files]
  copy:
    src: ../../files/app/package-lock.json
    dest: /var/www/html/app/package-lock.json
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy package.json to server
  tags: [copy_files]
  copy:
    src: ../../files/app/package.json
    dest: /var/www/html/app/package.json
    owner: www-data
    group: www-data
    mode: 0644

# copy app.js to server
- name: Copy app.js to server
  tags: [copy_files]
  copy:
    src: ../../files/app/app.js
    dest: /var/www/html/app/app.js
    owner: www-data
    group: www-data

# copy service file to start app to server
- name: Create service file
  template:
    src: ../../files/node_app.service
    dest: /etc/systemd/system/node_app.service
  register: service_conf

# perform systemctl daemon-reload to register new service
- name: Reload systemd daemon
  tags: app, deploy, systemd
  systemd:
    daemon_reload: yes
  when: service_conf.changed

# install node app dependencies
- name: Install dependencies from lockfile
  shell: npm ci
  args:
    chdir: /var/www/html/app

# start node service
- name: Start NodeJS service
  service:
    name: node_app
    state: started
    enabled: yes
